### ISSUE TITLE
Document the JS

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs-sphinx-search#22]
We should generate API docs for our JS code. We could try this with [autoapi](https://sphinx-autoapi.readthedocs.io/) and if that doesn't work, we should try [sphinx-js](https://sphinx-js-howto.readthedocs.io/en/latest/)

**Comment by dojutsu-user** [comment]
@ericholscher 
[sphinx-autoapi](https://github.com/readthedocs/sphinx-autoapi) doesn't work (probably due to the incompatible version of jsdoc) and [sphinx-js](https://github.com/mozilla/sphinx-js) works but it doesn't generate docs for the whole file. We have to manually write functions in the docs for which we want the docs to be generated, like -- `.. js:autofunction:: someFunction`.

Should I proceed with [sphinx-js](https://github.com/mozilla/sphinx-js)?

**Comment by ericholscher** [comment]
I'd like to have it documented, I'd try with sphinx-js if it isn't too much work.
